### ISSUE TITLE
Add Stripped Bark blocks if Et Futurum is loaded.

### ISSUE THREAD

**Issue by MagmaSlime123** [Javanosa/MiddleEarth-Tweaks#1]
Title.

This kind of conflicts with Et Futurum's bark blocks. If this mod & Et Futurum are loaded, have Et Futurum's bark be disabled, and add stripped bark blocks to complement Et Futurum's Stripped wood. (Which only adds blocks for the 6 Vanilla woods.)

**Comment by Javanosa** [comment]
Thank you for your report and sorry for the late response. 

I have tested a bit and it seems that it adds both stripped wood and stripped log, and ET Futurum's Bark Blocks can be disabled in their config. 
(im technically not adding news blocks but just adding additional meta states to the inventory, crafting and block pick)

Maybe I misunderstood something

Currently, additional Stripped Log Blocks for LOTR Woods arent planned, we will see in the future.
