### ISSUE TITLE
ability to enable/disable ore generation

### ISSUE THREAD

**Issue by stormscourge** [Javanosa/MiddleEarth-Tweaks#2]
title. 

it'd be really great to have the ability to enable/disable the generation of specific ores. i.e being able to disable copper or tin from generating; as playing with other mods causes the issue of duplicate ore types.

**Comment by Javanosa** [comment]
What other mods do generate the tin/copper?

I can add a single option to disable copper, tin. Any other ore you would not like to generate?

**Comment by stormscourge** [comment]
there's a good list- Thermal Foundation, Mekanism, Tinkers' Construct, Et Futurum requiem, just to name a few.

having an option for copper, tin, & silver would be great! individual options for each ore would be preferred, but a blanket option is great too. (:

**Comment by Javanosa** [comment]
Version 1.3.10: https://curseforge.com/minecraft/mc-mods/lotr-middleearth-tweaks/files/5628346

metweaks-ASM.properties -> "disableTinCopperSilverGen"
