### ISSUE TITLE
a strange server crash when connecting to server

### ISSUE THREAD

**Issue by ahliu22** [Javanosa/MiddleEarth-Tweaks#4]
Hello I found a strange problem.The server can launch successfully with MiddleEarth Tweaks(all versions are ok).
But if I use v1.4 or above on the server,the server will crash when the client is trying to connect to it.
I have tried serveral times,and MT v1.3.11 or lower versions won't crash.
crucible server 
I'm not sure whether it is caused by other mods or the crucible server.I'm really confused :(

below are the server mod list and the crash report
![1](https://github.com/user-attachments/assets/e619c0e1-546c-4373-864c-f89abe496864)
![2](https://github.com/user-attachments/assets/f84a1218-1202-4c44-857c-d11998873d38)
![3](https://github.com/user-attachments/assets/c8197dc4-7ddd-4468-9e6b-085c13eeab10)

**Comment by Javanosa** [comment]
Some mod is messing with the instructiond of EntityPlayer.isCurrentToolAdventureModeExempt()

This is most likely a mod incompatibility. (Possibly fixable if we find out whats being done)

Can you try if it works when using Forge?

Also does it happen if you remove any of the mods: lotrla. I also dont know the other mods used.

Make a local test server for that

**Comment by ahliu22** [comment]
Ohhhhhhhhh it will not crash when using forge server!
Maybe there are some bugs when working with crucible server :(
Anyway,thank you very much!

**Comment by Javanosa** [comment]
I will take a look at their code. 

For now either use Forge or alternatively disable `metweaks-ASM.properties -> "improveBlockBreakSpeeds"` It controls some adventuremode stuff and lmproves some block break speeds for thatch, hay , slabs etc.

**Comment by Javanosa** [comment]
Could you open your server jar file as archive and send me the file `net/minecraft/entity/player/EntityPlayer.class` ?

**Comment by ahliu22** [comment]
Well,it will not crash on crucible server if I disable  "improveBlockBreakSpeeds".
But there isn't "net/minecraft/entity/player/EntityPlayer.class" file in the crucible server jar?
![cru](https://github.com/user-attachments/assets/f4c2e3d2-75d2-4b2c-8a6c-22610f07af1d)

**Comment by Javanosa** [comment]
Do you have other jar files in the same directory regarding the server? Are there files like abc.class in the root directory of the archives or in net/minecraft/?

**Comment by ahliu22** [comment]
there are no other jar files and none of them contains "net/minecraft/entity/player/EntityPlayer.class" in the jar 😰😰😰
![4](https://github.com/user-attachments/assets/7af0d821-c497-441a-bf9d-bed5d24c78a7)

**Comment by Javanosa** [comment]
I will take a look myself when i get to a computer. For now you will have to live with either Forge or disabling the metweaks-ASM.properties -> improveBlockBreakSpeeds config option

**Comment by Javanosa** [comment]
I cant reproduce it on Crucible 5.4 with lotrmod and metweaks. Can you try this debug build and paste the log output? [MiddleEarth-Tweaks-1.4.4.1-debug-only.jar](https://cdn.discordapp.com/attachments/917449290207592512/1314387415351300137/MiddleEarth-Tweaks-1.4.4.1-debug-only.jar?ex=6753962b&is=675244ab&hm=1a3f8118bed58d8e7bb326fd173fd44eb7908d52488db2fced1da8ac47e7485b&)

**Comment by ahliu22** [comment]
sorry I can't open the website :(
<img width="998" alt="无标题" src="https://github.com/user-attachments/assets/dcdf9619-e6c3-42b2-b9a3-9de69596491e">

**Comment by Javanosa** [comment]
Try this: [MiddleEarth-Tweaks-1.4.4.1-debug-only.jar](http://jonosa.bplaced.net/shared) and share the log

**Comment by ahliu22** [comment]
It works well on forge server but still crashes on crucible server when the client is trying to connect to it :(
[crash-2024-12-13_19.17.41-server.txt](https://github.com/user-attachments/files/18125655/crash-2024-12-13_19.17.41-server.txt)

**Comment by Javanosa** [comment]
Im aware that it will still crash, i need the log output to know the class content. The crashlog doesnt contain that

**Comment by ahliu22** [comment]
[log-12.13.zip](https://github.com/user-attachments/files/18160165/log-12.13.zip)

**Comment by Javanosa** [comment]
Thank you. 
For some reason, the transformer is receiving the class EntityPlayer 7 times instead of just once..   Not sure why
Could you try [MiddleEarth-Tweaks-1.4.7.1-beta.jar](http://jonosa.bplaced.net/shared/) if that fixes the crash?

**Comment by ahliu22** [comment]
I give up using crucible server :(
[1226.zip](https://github.com/user-attachments/files/18266484/1226.zip)

**Comment by Javanosa** [comment]
So the only solution for now is using the latest metweaks version and turning off `metweaks-ASM.properties -> adventureModePatches` if you still wanna use crucible server
